
version: '3.8'

networks:
  default:

services:
  next-app:
    container_name: docker-crud
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - ${NEXTJS_APP_LOCAL_PORT}:${NEXTJS_APP_DOCKER_PORT}
    stdin_open: true
    tty: true
    volumes:
      - ./crud-app:/app
      - /app/node_modules
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: crud-db
    ports:
      - '3306:3306'
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $${MYSQL_ROOT_USER} --password=$${MYSQL_ROOT_PASSWORD}
      timeout: 20s
      retries: 10

volumes:
  db:
    driver: local