import "@/styles/global.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import AuthProvider from "./auth/Provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.variable}>
        <AuthProvider>
          <main className="p-5">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
